### ISSUE TITLE
Access redirects case-insensitive

### ISSUE THREAD

**Issue by thomasdigby** [shortlist-digital/tapestry-lite#76]
A redirect of `{ '/Hello': '/something-else' }` should redirect correctly when going to `/hello`.

It currently redirects to `/undefined` as the object lookup isn't case insensitive.

**Comment by jonsherrard** [comment]
Strangely the router should case insensitive: https://github.com/shortlist-digital/tapestry-lite/blob/69232a5b60b1a2e3d23abb2e20844f0fa4554ae3/src/server/index.js

**Comment by thomasdigby** [comment]
Yeah it's a bug with our `setRedirects` method, we're looking up whether the redirect exists case-insensitively, but when we go to use the redirect we're looking on the redirects object case-sensitively.

https://github.com/shortlist-digital/tapestry-lite/blob/master/src/server/handlers/redirect.js#L17

**Comment by jonsherrard** [comment]
Aha! When we moved from settings loads of redirect routes, to doing a "pre Route handler" function ourselves. Good catch.

**Comment by thomasdigby** [comment]
Fixed in [1.5.2](https://github.com/shortlist-digital/tapestry-lite/tree/v1.5.2)
